const ASSESSMENT_EVENT_TYPES = {
  CAPTURE_INITIAL_IP: "IP_CAPTURED_INITIAL",
  CAPTURE_FINAL_IP: "FINAL_IP_CAPTURED",
  SUBMITTED: "ASSESSMENT_SUBMITTED",
  IP_CHANGE: "LIKELY_BENIGN",
  REGION_CHANGE: "SUSPICIOUS",
  IP_CHANGE_WARNING_SHOWN: "IP_CHANGE_WARNING_SHOWN",
  ANSWER_SELECTED: "ANSWER_SELECTED",
  QUESTION_VIEWED: "QUESTION_VIEWED",
  TAB_VISIBILITY_CHANGE: "TAB_VISIBILITY_CHANGE",
  RETURNED_TO_ASSESSMENT: "RETURNED_TO_ASSESSMENT",
  TAB_SWITCH_DETECTED: "TAB_SWITCH_DETECTED",
  IP_CHECK_PERFORMED: "IP_CHECK_PERFORMED",
  SAME_IP: "SAME_IP",
  DIFFERENT_IP: "DIFFERENT_IP",
  IP_CHANGE_DETECTED: "IP_CHANGE_DETECTED",
  IP_CHANGE_CLASSIFIED: "IP_CHANGE_CLASSIFIED",
};

const ASSESSMENT_STATUS = {
  SUBMIT: "SUBMITTED",
  IN_PROGRESS: "ACTIVE",
};
export { ASSESSMENT_EVENT_TYPES, ASSESSMENT_STATUS };
